// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxbjksrtdhromprpwwer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4Ymprc3J0ZGhyb21wcnB3d2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1OTQwMDYsImV4cCI6MjA1ODE3MDAwNn0.9iuGcs2u6NI0fRp3sV2Jxbful6fI-X3hGqGLJuqftQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);